### ISSUE TITLE
Camera Search not working in DeviceManager

### ISSUE THREAD

**Issue by enesbcs** [NeiroNx/python-dvr#14]
In DeviceManager.py when i try to search for cameras on my local network, nothing found.
The GetAllAddr() function correctly gets my IP address, and it is on the same subnet, as the camera.
Although when i injecting address= '0.0.0.0' line before server.bind() line in SearchXM() function, then it is able to receive response from camera, and displays them correctly.

I recommend to use '0.0.0.0' to bind all interface at once when searching, instead of the current GetAllAddr() method.
My quickfix looks like this:

```
def GetAllAddr():
    return ['0.0.0.0']
```

**Comment by den2487** [comment]
> In DeviceManager.py when i try to search for cameras on my local network, nothing found.
> The GetAllAddr() function correctly gets my IP address, and it is on the same subnet, as the camera.
> Although when i injecting address= '0.0.0.0' line before server.bind() line in SearchXM() function, then it is able to receive response from camera, and displays them correctly.
> 
> I recommend to use '0.0.0.0' to bind all interface at once when searching, instead of the current GetAllAddr() method.
> My quickfix looks like this:
> 
> ```
> def GetAllAddr():
>     return ['0.0.0.0']
>
 ```
I have same problem, thanks for the elegant solution, it works great

**Comment by enesbcs** [comment]
Thanks! I am not sure if it is working for multiple network interfaces, but with single device it works fine. https://github.com/enesbcs/python-dvr/commit/03785596cce87ab2da3dd279b1485ee6aae47da0
