### ISSUE TITLE
Video stream access?

### ISSUE THREAD

**Issue by linknum23** [NeiroNx/python-dvr#15]
Maybe I missed something but have you had any luck using this to get access to the video stream? The camera that I am using has terrible latency over rtsp > 1s but near real time latency with the activex plugin, so access to the activex video stream would be very useful.

**Comment by NeiroNx** [comment]
I am not planed to do this because it too hard for me. If you need you can do this: just sart new connection, first packet is init connection type, recive packets is 20 byte head and body is h264 stream part. Stream buffering and decoding it - hard part.
