### ISSUE TITLE
AttributeError: 'DVRIPCam' object has no attribute 'set'

### ISSUE THREAD

**Issue by passele** [NeiroNx/python-dvr#19]
Hi,

Trying to use python-dvr to set an IP camera I got the error below:

 File "/home/pi/Desktop/dvrip.py", line 474, in set_info
    return self.set(1040, command, data)
AttributeError: 'DVRIPCam' object has no attribute 'set'

Veryfying the code on the drvip.py file, I noticed that there really isn't a definition for the "set" method.
I locally created the method and it worked perfectly, but it's lacking on the repository.

Thank you for the great work.

**Comment by widgetii** [comment]
Hi! How can I reproduce the issue?

**Comment by passele** [comment]
Just call any method that calls the set method of the DVRIPCam class. For example, like this:

import sys
from dvrip import DVRIPCam
from time import sleep
import json

#FILL IN YOUR DETAILS HERE:
CameraUserName = "admin"
CameraPassword = ""
CameraIP = '192.168.0.97'
BitrateRequired = 7000
#END OF USER DETAILS


if len(sys.argv) > 1:
    CameraIP = str(sys.argv[1])

cam = DVRIPCam(CameraIP,CameraUserName,CameraPassword)

if cam.login():
    print ("Success! Connected to " + CameraIP)
else:
    print ("Failure. Could not connect to camera!")

sleep(2)
print ("\r\n")
print ("Current encoding settings:")

enc_info = cam.get_info("Camera")
print (enc_info)
print ("----------------------\r\n")

enc_info['Param'][0]['PictureFlip'] =  '0x00000001'
print (enc_info)
print ("----------------------\r\n")

cam.set_info('Camera' , enc_info)      # <<--- This line line calls set_info() which calls set() in dvrip,py, line 474
cam.close()

The error:

  File "/home/pi/Desktop/dvrip.py", line 474, in set_info
    return self.set(1040, command, data)
AttributeError: 'DVRIPCam' object has no attribute 'set'

The error occurs at line 474 of the dvrip.py file. It calls self.set (1040, command, data) and this self.set() method does not exist in the DVRIPCam  class.

Checking out old releases of dvrip.py this self() method exists. For example, https://github.com/NeiroNx/python-dvr/blob/7ba392e0faa1f09175109ffdf935c066dae93352/dvrip.py, in line 460 the method is defined.

In the most recent release of dvrip.py (https://github.com/NeiroNx/python-dvr/blob/66cab2e3fb79ed92ce2c87d73e3ff37c3f6a3da4/dvrip.py) this set() method was lost.

**Comment by widgetii** [comment]
Please check latest master

**Comment by passele** [comment]
Dimitri,

No. Now  I have the error: 

Traceback (most recent call last):
  File "/home/pi/Desktop/teste2.py", line 37, in <module>
    cam.set_info('Camera' , enc_info) # <<--- This line line calls set_info() which calls set() in dvrip,py, line 474
  File "/home/pi/Desktop/dvrip.py", line 473, in set_info
    return self.set_command(1040, command, data)
  File "/home/pi/Desktop/dvrip.py", line 483, in set_command
    code, {"Name": command, "SessionID": "0x%08X" % self.session, command: data}
  File "/home/pi/Desktop/dvrip.py", line 148, in send
    + b"\x0a\x00"
struct.error: required argument is not an integer

![image](https://user-images.githubusercontent.com/78766178/107407878-fcbaf580-6ae8-11eb-9c2b-93def75dd2a1.png)

The problem now is that in dvrip.py, on line 473 the set_command method is called with the parameters (code, command, data) and on it's definition the signature of its parameters on line 479 is defined as (command, data, code). 

If I change in line 473 and call self.set_command (command, data, 1040), it works fine in my case, but there are other calls in the code where the parameters might be twisted.

**Comment by widgetii** [comment]
Please check again, tested on your code

**Comment by passele** [comment]
Hi, 

On this point, the correction worked well. 
There are other calls to set_command that also need to be corrected.
I can correct them on my machine, when I need to. But whoever downloads the code on github will have problems.

Thank you, bye.
