### ISSUE TITLE
Error when the 'data' parameter is not set when calling self.send(msg, data, ...)

### ISSUE THREAD

**Issue by lemeur** [NeiroNx/python-dvr#22]
data has no default value anymore (this has been changed in a previous version) of the `dvrip.py`file

Adding a default value fixes the issue, for instance:
```
158     def send(self, msg, data=[], wait_response=True):
```

there are several occurences of calling self.send() without a value for the data parameter in the `dvrip.py`file:
```
218     def getAuthorityList(self):
219         data = self.send(self.QCODES["AuthorityList"])

...

225     def getGroups(self):
226         data = self.send(self.QCODES["Groups"])

...
271     def getUsers(self):
272         data = self.send(self.QCODES["Users"])

```

**Comment by widgetii** [comment]
Thank you, for bug report, hopefully fixed
