### ISSUE TITLE
PTZ step move

### ISSUE THREAD

**Issue by petkok** [NeiroNx/python-dvr#27]
Hi, 10x for code you made available!

I'm trying to move my digoo bb-m1 cam
by using cam.ptz('DirectionUp', preset=0, step=1), but
instead of moving just a step my cam moves to upper most position.
What did I do wrong , help pls?

**Comment by petkok** [comment]
Ok I found solution, commands must be called in pairs like that:
params= cam.ptz( "DirectionUp",preset=0)
params= cam.ptz( "DirectionUp",preset=-1)

**Comment by NeiroNx** [comment]
https://github.com/NeiroNx/python-dvr/blob/53095644844f9666edc9da50d644431f49eec774/dvrip.py#L523

it always call "Start" may be need booth: "Start" and then "Stop"

**Comment by petkok** [comment]
I've tried "Pattern": "Start" and then "Pattern": "Stop" but that didn't help. Then I used wireshark to spy commands from CMS app and found that they use preset=-1 to stop the motion.

**Comment by function1983** [comment]
```
params= cam.ptz( "DirectionUp",preset=0, ch=0)
time.sleep(2)
params= cam.ptz( "DirectionUp",preset=-1, ch=0)
```
This helps pan the camera for 2 seconds then stop panning.
