### ISSUE TITLE
Feature Proposal - OPFeederFunctions

### ISSUE THREAD

**Issue by MateoGreil** [NeiroNx/python-dvr#36]
Hello,

I'm currently adding OPFeederFunctions, they are available on pet food dispenser.
I'm currently testing and developing for this pet food dispenser :
<details>
  <summary>Maginon Feed Dispenser AFS-1</summary>
  
```python
>>> cam.get_system_info()
{'AlarmInChannel': 0, 'AlarmOutChannel': 0, 'AudioInChannel': 1, 'BuildTime': '2019-09-18 15:27:23', 'CombineSwitch': 0, 'DeviceModel': '', 'DeviceRunTime': '0x000016F0', 'DeviceType': 24, 'DigChannel': 0, 'EncryptVersion': 'Unknown', 'ExtraChannel': 0, 'HardWare': 'HI3516EV100_53H13L_FD_F4', 'HardWareVersion': 'Unknown', 'SerialNo': 'af2b2038e9906093', 'SoftWareVersion': 'V4.03.R12.0002299E.12002.044602.0000000', 'TalkInChannel': 1, 'TalkOutChannel': 1, 'UpdataTime': '', 'UpdataType': '0x00000000', 'VideoInChannel': 1, 'VideoOutChannel': 1}
```

</details>

But I guess these functions are available on all IPC with food dispenser on NetSurv.

Let me know if you are interesting about merging my futures adds on your project.
You can follow the dev here : https://github.com/MateoGreil/python-dvr-n-feed/pull/1 [WIP].

**Comment by widgetii** [comment]
Sure, it's very interesting, but I personally don't have such device for tests.

Feel free to inform when you're ready to merge your improvements.

**Comment by MateoGreil** [comment]
Ok nice !
