### ISSUE TITLE
Change the settings of the camera

### ISSUE THREAD

**Issue by shadowbgd** [NeiroNx/python-dvr#4]
Hi, I have camera module:
https://www.aliexpress.com/item/32931149901.html?spm=a2g0s.9042311.0.0.4c1f4c4dBaNE9j

your code works with this camera, but I'm trying to add functions to set turn on/off AGC settings.
Also, I would like to have controls for ZOOM and FOCUS.

Using Wireshark tool, I was able to capture command for settings:

....	...............{ "Camera.ParamEx.[0]" : { "AeMeansure" : 0, "AutomaticAdjustment" : 3, "BroadTrends" : { "AutoGain" : 1, "Gain" : 50 }, "CorridorMode" : 0, "Dis" : 0, "ExposureTime" : "0x00000100", "Ldc" : 0, "LightRestrainLevel" : 16, "LowLuxMode" : 0, "PreventOverExpo" : 0, "SoftPhotosensitivecontrol" : 0, "Style" : "type2" }, "Name" : "Camera.ParamEx.[0]", "Ret" : 100, "SessionID" : "0x00000009" }

.....	...........I...{ "Camera.Param.[0]" : { "AeSensitivity" : 7, "ApertureMode" : "0x00000001", "BLCMode" : "0x00000001", "DayNightColor" : "0x00000000", "Day_nfLevel" : 3, "DncThr" : 30, "ElecLevel" : 50, "EsShutter" : "0x00000006", "ExposureParam" : { "LeastTime" : "0x00000064", "Level" : 0, "MostTime" : "0x00010000" }, "GainParam" : { "AutoGain" : 0, "Gain" : 50 }, "IRCUTMode" : 1, "IrcutSwap" : 0, "Night_nfLevel" : 3, "PictureFlip" : "0x00000001", "PictureMirror" : "0x00000001", "RejectFlicker" : "0x00000000", "WhiteBalance" : "0x00000000" }, "Name" : "Camera.Param.[0]", "SessionID" : "0x9" }

But I didn't figure out how to send this to the camera. Can you help me?

I have attached whole TCP Stream of commands from camera and to camera if you need it
[starlight kamera.txt](https://github.com/NeiroNx/python-dvr/files/3531267/starlight.kamera.txt)

**Comment by NeiroNx** [comment]
```python
#!/usr/bin/env python
# -*- coding: UTF-8 -*-

from dvrip import DVRIPCam
import json

host_ip = '192.168.0.100'

cam = DVRIPCam(host_ip,"admin","pass")

if cam.login():
	print("Success! Connected to " + host_ip)
else:
	print("Failure. Could not connect.")

#read it
info1 = cam.get_info("Camera.ParamEx.[0]")
info2 = cam.get_info("Camera.Param.[0]")
#just view in console
print(json.dumps(info1, ensure_ascii=False))
print(json.dumps(info2, ensure_ascii=False))
#may be (need see printout)
info1["Camera.ParamEx.[0]"]["BroadTrends"]["AutoGain"] = 1
info1["Camera.ParamEx.[0]"]["BroadTrends"]["Gain"] = 50
#and write it
cam.set_info("Camera.ParamEx.[0]", info1)
cam.set_info("Camera.Param.[0]", info2)
cam.close()
```

**Comment by shadowbgd** [comment]
Thanks!
