### ISSUE TITLE
stop_monitor() no work

### ISSUE THREAD

**Issue by Vasiliy1992** [NeiroNx/python-dvr#43]
Hello.
How can I disable the DVR using your library 'python-dvr'?

**cam.reboot()** - Reboot works
**cam.stop_monitor()** - Shutdown - no work.

**My DVR:**
**Model**: SAE3000-N1408F
**System**: V4.03.R11.16800203.12001.130000.000000
**Build Date**: 2021-04-29

![SMAR](https://github.com/NeiroNx/python-dvr/assets/83471500/760ccd30-18c3-4a0f-b891-6f4eb68a7f49)

**Comment by widgetii** [comment]
`stop_monitor()` is not a device shutdown, it's a stop action for incoming media data

**Comment by Vasiliy1992** [comment]
Is there a way to programmatically disable the DVR?

**Comment by widgetii** [comment]
I don't know such way

**Comment by Vasiliy1992** [comment]
Has anyone tried running this script?

`python3 telnet_opener.py -h
usage: telnet_opener.py [-h] [-u USERNAME] [-p PASSWORD] [-b] [-t] hostname

positional arguments:
  hostname              Camera IP address or hostname

optional arguments:
  -h, --help            show this help message and exit
  -u USERNAME, --username USERNAME
                        Username for camera login
  -p PASSWORD, --password PASSWORD
                        Password for camera login
  -b, --backup          Make backup to the cloud
  -t, --telnet          Open telnet port without rebooting camera
`

It issues a request to flash the registrar. I did not dare to start the process.

`
Modifying camera NBD8004R-PL, firmware 16800203
Current firmware date 2021-04-29, but it needs to be no more than 2020-05-07
Consider downgrade and only then continue.


Are you sure to overwrite current firmware without backup (y/n)? 
`

**Comment by widgetii** [comment]
This will work only for IP camera

**Comment by NeiroNx** [comment]
If you flash(erase) "user" partition which contains main software "sofia" - you disable it forewer.
