### ISSUE TITLE
alarm notification

### ISSUE THREAD

**Issue by Innocentius-alt** [NeiroNx/python-dvr#45]
Hello!

Thank you for great job. i am kind of noobish in programming, so excuse me for this question.

How can i get notification from my cam (e. g. motion detect) to trigger some further actions?
Something like this:
```
if cam.get_notification('motion detect'):
      some_useful_function()
```

Thank you in advance

**Comment by verminoid** [comment]
you can make a notification server (see module "AlarmServer").  The camera will need to be configured accordingly to send notifications (can often be done via the camera gui).  when receiving a message, do your further code

**Comment by Innocentius-alt** [comment]
> you can make a notification server (see module "AlarmServer"). The camera will need to be configured accordingly to send notifications (can often be done via the camera gui). when receiving a message, do your further code

great thanks!! it really works! i just replace line 43 in AlarmServer.py  with:
```
`        data = data.decode("utf-8")
        reply = json.loads(data)
```

and happiness came to me))
