### ISSUE TITLE
Any way to get video stream?

### ISSUE THREAD

**Issue by parkerlreed** [NeiroNx/python-dvr#5]
I have an IPC365 (at least what it identities as over telnet). Camera is completely unbranded. It came with box and is a cheap Philips rebadge (I think it was Philips. I lost the box already)

Official application is "SHOWMO"

Login is root:noty as noted here https://forums.hak5.org/topic/40819-best-way-to-hack-ip-camera/

I have been able to access the stream two ways

Port 34567, username admin, password 123456

* IP Cam Viewer mobile application. Model "A.V. Sistemi 61xx DVR"
* CMS on Windows XP 

![image](https://user-images.githubusercontent.com/841440/64931416-9a33cc00-d806-11e9-80d3-c9d6ed81575c.png)

Outside of that, nothing. 34567 appears to be a multi function video/audio/config port

This is all handled by 

```
  250 root       608 S    dvrHelper /lib/modules /var/Alloca 127.0.0.1 9578 1
```

Got a capture from the CMS application of it starting a session and a rootfs backup (block2 is the main)

https://drive.google.com/drive/folders/1Ma6ue32uc6FWHJ0Z5J_vPYNn6ucdHTem?usp=sharing

And luckily your script can talk to it

```
>>> from dvrip import DVRIPCam
>>> from time import sleep
>>> cam = DVRIPCam("192.168.86.133","admin","123456")
>>> cam.login()
True
>>> time = cam.get_time()
>>> print "CAM Time:",time
CAM Time: 2019-09-15 21:56:03
>>> cam.reboot()
```

All of which worked.

Any ideas on how I can just get a stream out of this in a sane way? I'd prefer basic HTTP/RTSP but the web server on port 80 is blank. The special port is the only way I've found to access it.

**Comment by parkerlreed** [comment]
Ok so https://github.com/eloygn/IT_Security_Research_WirelessIP_camera_family

Point out that 22334 is the RTSP port and the 9527 leaks the creds. I haven't been able to find a way to generate as the allude and get the stream.

**Comment by NeiroNx** [comment]
If you need that - you can write that.

**Comment by parkerlreed** [comment]
Aye. I was planning on it. Just wanted to see if there was an easy existing method/script to startup the RTSP stream before I sunk some time into getting it working.

Thanks.

**Comment by xeroxoid** [comment]
@parkerlreed did you ever find that stream url? I have a similar camera and can telnet to it and it also has 2 other open ports: 23456 and 34567.

What settings did you use for IP Cam Viewer? Tried multiple channels and both ports with no luck..

![Example](https://ibin.co/5TcuOtz6Fz9C.png)

Did you manage to get it working with the python-dvr lib script?

**Comment by parkerlreed** [comment]
You got the password in there?

Port 34567, username admin, password 123456

**Comment by xeroxoid** [comment]
> You got the password in there?
> 
> Port 34567, username admin, password 123456
> 
> I never got that working anywhere else

Yeah, got the password in but the iOS screenshot removes the dots 😋 

Well it doesn't connect for me. Might be another firmware version.

Been trying out the script too but am getting a timeout...

```
timed out
{'Ret': 101}
Traceback (most recent call last):
  File "test.py", line 22, in <module>
    if cam.login():
  File "...../python-dvr/dvrip.py", line 170, in login
    self.session = int(data["SessionID"], 16)
KeyError: 'SessionID'
```

I guess 101 is an unknown error so the script can't seem to even login.

**Comment by Pre10der** [comment]
@xeroxoid - Did you ever get IP Cam Viewer to render the stream? I too have a few of these cameras I would like to leverage, but ran into the same issue you have noted with the iOS app. I note you have another project going to try and tackle this also.

**Comment by xeroxoid** [comment]
> @xeroxoid - Did you ever get IP Cam Viewer to render the stream? I too have a few of these cameras I would like to leverage, but ran into the same issue you have noted with the iOS app. I note @Toxblh has another project going to try and tackle this also: [https://github.com/Toxblh/hack-my-ipc](url)

Unfortunately not.. I gave up at some point, looking at getting an Eufy or similar with Homekit support.

**Comment by Toxblh** [comment]
> @xeroxoid - Did you ever get IP Cam Viewer to render the stream? I too have a few of these cameras I would like to leverage, but ran into the same issue you have noted with the iOS app. I note @Toxblh has another project going to try and tackle this also: [https://github.com/Toxblh/hack-my-ipc](url)

Nope. Only if find compatible firmware and load inside. Because flash(sd) is encrypted + Alloca has connected to amazon and restream under encryption as tunnelling to the cloud/app, without any RTSP or other open ports/streams. I tried to find in configs some debug mode or similar and nothing. In the end, the camera is dead and I bought aqara G2H for the HomeKit 
Sad story.

**Comment by GianSeven** [comment]
For anyone still interested in this. I was able to get an HTTP streaming out of this device. Both audio and video work. I don't know if my device was easier to access but it's really simple. I arrived at this solution randomly but here's what I think:
This camera uses a protocol called dvrip. I've used https://github.com/AlexxIT/WebRTC
This Home Assistant integration uses WebRTC + go2rtc which is able to talk to this protocol I presume
If you are confused from what this "Home Assistant integration" is, look into Home Assistant first.

I'll explain what I did from after the GitHub guide ends
After the configuration (of the 'basic' version) of go2rtc. It gets its own port, 1984.
Write <homeassistant-ip>:1984 in a browser just like you do with :8123 to access Home Assistant
Here click "Add", then open "temponary stream" 
```
Name: (What you want, you'll need it later, I put IPC365) 
url: dvrip://admin:123456@<IP Address of the camera>?channel=0&subtype=0
```
Remember that the IP address should be static or this configuration will get broken later on, you can likely do that from your router
Go back to Home Assistant, click on the kebab (3 dots) in the top right to access "Edit dashboard", then on the bottom right "+ Add cards", scroll to the bottom to find "Manual". Paste all of this
```
type: custom:webrtc-camera
url: IPC365 <---- The name you had to put in before
ui: true
digital_ptz:
  mouse_drag_pan: true
  mouse_wheel_zoom: true
  mouse_double_click_zoom: true
  touch_drag_pan: true
  touch_pinch_zoom: true
  touch_tap_drag_zoom: true
  persist: true
title: What you want
muted: true
intersection: 0.75
background: false
shortcuts:
  - name: Record
    icon: mdi:record-circle-outline
    service: switch.toggle
    service_data:
      entity_id: switch.camera_record
mode: webrtc,mse,hls,mjpeg
```

As you can see here url: is the name I have given it before in the go2rtc interface

Feel free to contact me if you need help, english isn't my first language

**Comment by aschwehm** [comment]
> For anyone still interested in this. I was able to get an HTTP streaming out of this device. Both audio and video work. I don't know if my device was easier to access but it's really simple. I arrived at this solution randomly but here's what I think: This camera uses a protocol called dvrip. I've used https://github.com/AlexxIT/WebRTC This Home Assistant integration uses WebRTC + go2rtc which is able to talk to this protocol I presume If you are confused from what this "Home Assistant integration" is, look into Home Assistant first.
> 
> I'll explain what I did from after the GitHub guide ends After the configuration (of the 'basic' version) of go2rtc. It gets its own port, 1984. Write :1984 in a browser just like you do with :8123 to access Home Assistant Here click "Add", then open "temponary stream"
> 
> ```
> Name: (What you want, you'll need it later, I put IPC365) 
> url: dvrip://admin:123456@<IP Address of the camera>?channel=0&subtype=0
> ```
> 
> Remember that the IP address should be static or this configuration will get broken later on, you can likely do that from your router Go back to Home Assistant, click on the kebab (3 dots) in the top right to access "Edit dashboard", then on the bottom right "+ Add cards", scroll to the bottom to find "Manual". Paste all of this
> 
> ```
> type: custom:webrtc-camera
> url: IPC365 <---- The name you had to put in before
> ui: true
> digital_ptz:
>   mouse_drag_pan: true
>   mouse_wheel_zoom: true
>   mouse_double_click_zoom: true
>   touch_drag_pan: true
>   touch_pinch_zoom: true
>   touch_tap_drag_zoom: true
>   persist: true
> title: What you want
> muted: true
> intersection: 0.75
> background: false
> shortcuts:
>   - name: Record
>     icon: mdi:record-circle-outline
>     service: switch.toggle
>     service_data:
>       entity_id: switch.camera_record
> mode: webrtc,mse,hls,mjpeg
> ```
> 
> As you can see here url: is the name I have given it before in the go2rtc interface
> 
> Feel free to contact me if you need help, english isn't my first language

I have tried this using just go2rtc directly.
go2rtc is giving me an error when trying to connect to the camera:
`23:20:58.815 ERR github.com/AlexxIT/go2rtc/internal/mjpeg/init.go:166 > error="streams: read tcp 10.69.1.21:48496->10.69.1.22:34567: i/o timeout"`
go2rtc provied support for dvrip. Maybe its just my camera. (Apeman ID73)

**Comment by GianSeven** [comment]
> I have tried this using just go2rtc directly. go2rtc is giving me an error when trying to connect to the camera: `23:20:58.815 ERR github.com/AlexxIT/go2rtc/internal/mjpeg/init.go:166 > error="streams: read tcp 10.69.1.21:48496->10.69.1.22:34567: i/o timeout"` go2rtc provides support for dvrip. Maybe its just my camera. (Apeman ID73)

I know that go2rtc can be configured with different parameters during install, in guides for running it in home assistant it is said to go with the base config if you don't know what other things do. Maybe that configuration, whatever it is, is making it work, or maybe we have different cameras. I bought mine around 2016-17. Is yours much newer. Try a different name or password to see if it's refusing that. I don't know much about linux and networking but maybe you have to give permission to listen to the receiver port?
