### ISSUE TITLE
Get zoom level?

### ISSUE THREAD

**Issue by shadowbgd** [NeiroNx/python-dvr#6]
Is it possible to get the current zoom position?

**Comment by NeiroNx** [comment]
not possible, but i am not shure.
Camera have "OPPTZControl" but i am do not know how it work.

**Comment by nvrstyle** [comment]
> Is it possible to get the current zoom position?
Hi, happened get current zoom position or other ptz position?

**Comment by NeiroNx** [comment]
is not possible.
