### ISSUE TITLE
 Hello Friend,  How could I change the channel title of my DVR? I didn't get the correct parameter.

### ISSUE THREAD

**Issue by Wifibus** [NeiroNx/python-dvr#7]

**Comment by Wifibus** [comment]
I can change first  channel using: cam.channel_title( "teste") but  i´m try other channel, no sucess.

**Comment by Wifibus** [comment]
analisys by wireshark using CMS:

0040   00 00 00 00 16 04 90 00 00 00 7b 20 22 43 68 61   ..........{ "Cha
0050   6e 6e 65 6c 54 69 74 6c 65 22 20 3a 20 5b 20 22   nnelTitle" : [ "
0060   32 2e 74 65 73 74 65 22 2c 20 22 22 2c 20 22 34   2.teste", "", "4
0070   35 34 22 2c 20 22 22 2c 20 22 22 2c 20 22 22 2c   54", "", "", "",
0080   20 22 22 2c 20 22 22 2c 20 22 22 2c 20 22 22 2c    "", "", "", "",
0090   20 22 22 2c 20 22 22 2c 20 22 22 2c 20 22 22 2c    "", "", "", "",
00a0   20 22 22 2c 20 22 22 20 5d 2c 20 22 4e 61 6d 65    "", "" ], "Name
00b0   22 20 3a 20 22 43 68 61 6e 6e 65 6c 54 69 74 6c   " : "ChannelTitl
00c0   65 22 2c 20 22 53 65 73 73 69 6f 6e 49 44 22 20   e", "SessionID" 
00d0   3a 20 22 30 78 31 22 20 7d 0a                     : "0x1" }.

**Comment by Wifibus** [comment]
in dvrip.py  i change line : 
self.send(self.QCODES["ChannelTitle"],{ 'ChannelTitle' : ["a","s"],  "Name":"ChannelTitle","SessionID":"0x%08X"%self.session})   

I had sucess in changes, 2 channels be modiefied.. now  i need  learn a sintaxe for the  command

**Comment by NeiroNx** [comment]
https://github.com/NeiroNx/python-dvr/commit/27fb9dc8126d5bc99f019e6dddd2d9cb91c68d11#diff-2fbf4043e148c018e06b9ffb78f725bdR107
